### PR TITLE
[master] recommend fuse-overlayfs for Debian too

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Debian kernel has a non-upstream modprobe option `permit_mounts_in_userns=1` for kernel-mode overlayfs, but seems unstable: moby/moby#42302

So we should recommend fuse-overlayfs for Debian (until the release of Debian 12, which will support genuine kernel-mode overlayfs with kernel >= 5.11).

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
CI failure should be fixed in https://github.com/moby/moby/pull/42797

```
---> Making bundle: dynbinary (in bundles/dynbinary)
Building: bundles/dynbinary-daemon/dockerd-0.0.0-20210825074926-1fdafcd
GOOS="" GOARCH="" GOARM=""
# github.com/docker/docker/pkg/plugins
/go/src/github.com/docker/docker/pkg/plugins/discovery.go:44:12: undefined: fs.FileInfoToDirEntry
make[1]: *** [debian/rules:8: override_dh_auto_build] Error 2
make[1]: Leaving directory '/root/build-deb'
make: *** [debian/rules:102: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make: *** [Makefile:76: ubuntu-focal] Error 2
```
https://ci-next.docker.com/public/blue/organizations/jenkins/docker-ce-packaging/detail/PR-572/3/pipeline

File: deb/common/control [hunk 1]
```diff
@@ -92,9 +92,9 @@ Conflicts: rootlesskit
 Replaces: rootlesskit
 Breaks: rootlesskit
 # slirp4netns (>= 0.4.0) is available in Debian since 11 and Ubuntu since 19.10
-Recommends: slirp4netns (>= 0.4.0)
-# Unlike RPM, DEB packages do not contain "Recommends: fuse-overlayfs (>= 0.7.0)" here,
-# because Debian (since 10) and Ubuntu support the kernel-mode rootless overlayfs.
+# fuse-overlayfs is recommended for Debian 10 and 11 (kernel < 5.11). Not needed for Ubuntu.
+Recommends: slirp4netns (>= 0.4.0),
+            fuse-overlayfs (>= 0.7.0)
```
Comment (thaJeztah) [inline deb/common/control:97]: This control file is used for both Debian an Ubuntu; can we make this somehow conditional for Debian only? I recall we had some conditional rule for AppArmor on Debian that I removed in https://github.com/docker/docker-ce-packaging/pull/487 - perhaps a similar rule would work for this?

Comment (AkihiroSuda) [reply deb/common/control:97]: Modifying the file with `echo ... >> control` doesn't look robust. So I'd prefer to recommend fuse-overlayfs unconditionally.

Comment (thaJeztah) [reply deb/common/control:97]: It's creating a `.substvars` file (not modifying the `control` file)

**Comment by thaJeztah** [comment]
@tianon PTAL; perhaps you have suggestions on how to make this conditional for Debian (but not Ubuntu) in a clean way?

**Comment by tianon** [comment]
Indeed - the approach that was removed in #487 (`override_dh_gencontrol` writing into `debian/docker-ce-rootless-extras.substvars`) is definitely "correct".

Something like this: (untested :innocent:)

```diff
diff --git a/deb/common/control b/deb/common/control
index 0b5ed4a..34de085 100644
--- a/deb/common/control
+++ b/deb/common/control
@@ -94,9 +94,8 @@ Conflicts: rootlesskit
 Replaces: rootlesskit
 Breaks: rootlesskit
 # slirp4netns (>= 0.4.0) is available in Debian since 11 and Ubuntu since 19.10
-Recommends: slirp4netns (>= 0.4.0)
-# Unlike RPM, DEB packages do not contain "Recommends: fuse-overlayfs (>= 0.7.0)" here,
-# because Debian (since 10) and Ubuntu support the kernel-mode rootless overlayfs.
+# fuse-overlayfs is recommended for Debian 10 and 11 (kernel < 5.11). Not needed for Ubuntu.
+Recommends: slirp4netns (>= 0.4.0~), ${fuse-overlayfs:Recommends}
 Description: Rootless support for Docker.
   Use dockerd-rootless.sh to run the daemon.
   Use dockerd-rootless-setuptool.sh to setup systemd for dockerd-rootless.sh .
diff --git a/deb/common/rules b/deb/common/rules
index 9b495e9..50a95da 100755
--- a/deb/common/rules
+++ b/deb/common/rules
@@ -3,6 +3,11 @@
 VERSION ?= $(shell cat engine/VERSION)
 TARGET_ARCH = $(shell dpkg-architecture -qDEB_TARGET_ARCH)
 
+override_dh_gencontrol:
+	# if we're not on Ubuntu, we need to Recommends: fuse-overlayfs in docker-ce-rootless-extras
+	echo 'fuse-overlayfs:Recommends=$(shell dpkg-vendor --is Ubuntu || echo 'fuse-overlayfs (>= 0.7.0~)')' >> debian/docker-ce-rootless-extras.substvars
+	dh_gencontrol
+
 # force packages to be built with xz compression, as Ubuntu 21.10 and up use
 # zstd compression, which is non-standard, and breaks 'dpkg-sig --verify'
 override_dh_builddeb:
```

(The trailing `~` on the version numbers allows them to be satisfied by backports if necessary too :+1:)

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda could you have a look at Tianon's suggestion?

Thanks, SGTM, but I haven't tested it

**Comment by AkihiroSuda** [comment]
Debian 12 is shipped with kernel 6.1, so I'm closing this
